### ISSUE TITLE
translation

### ISSUE THREAD

**Issue by epgeroy** [jkazama/sample-boot-hibernate#17]
congratulations is a very complete project and I'm grateful for you make it open source, can you please provide a english translation for you readme. I would like to take a closer look, but many compilation errors came up and I can't read Japanese.
Thanks in advance

**Comment by jkazama** [comment]
Hi, thanks for your request.
The domain of this repository is specialized for a Japanese, but makes English version in a branch if able to afford.

**Comment by jkazama** [comment]
I made an English branch. Please confirm it.
https://github.com/jkazama/sample-boot-hibernate/tree/en

**Comment by epgeroy** [comment]
It is perfect thanks a lot.
